### ISSUE TITLE
As a user when I visit the site link, I should be greeted with an informative home page before they proceed to creating an order a la the squarespace model

### ISSUE THREAD

**Issue by bolorundurowb** [bolorundurowb/project-fitted-ui#111]

**Comment by Saint-lawal** [comment]
What does this entail? @adetola-ralph @bolorundurowb

**Comment by bolorundurowb** [comment]
A home page that is visible when a user visits the site like the one the square space model had, then when the user wants to create an order then they see the map. I feel it is more user friendly because it caters to users who just want to check the site out as well as those who want to order
