### ISSUE TITLE
Order Details in Review/Fitting not showing

### ISSUE THREAD

**Issue by Saint-lawal** [bolorundurowb/project-fitted-ui#200]
- As an admin, when I click on an order to see details or start fitting/delivery, some details such as STYLING do not show.
- Also, add "Other" details to the review.

**Comment by adetola-ralph** [comment]
@Saint-lawal don't really understand this task.Can you please expatiate.

**Comment by Saint-lawal** [comment]
@adetola-ralph So if you try to run the fitting, when it brings the review of everything, you'll see some details are missing. That's one.
The other one is that when making a fitting or delivering, the comment made doesn't show in the order review. 
Makes sense?

**Comment by adetola-ralph** [comment]
> - Wrong picture
> - Info for measurements aren't showing
> - Other details not showing
> - Starting delivery doesn't change order status
