### ISSUE TITLE
remove time from order process

### ISSUE THREAD

**Issue by bolorundurowb** [bolorundurowb/project-fitted-ui#244]
Remove timing options when it comes to fitting time selection… instead,
have 3 dates choosable through a single calendar on the site

**Comment by adetola-ralph** [comment]
@bolorundurowb @Saint-lawal what is this task meant to be about. I thought he said he wanted time to be part of the fitting options. And 1 calendar to select all the fitting date (are we supposed to perform magic here?)

**Comment by bolorundurowb** [comment]
So we noticed that setting three separate days and times seemed to cumbersome for the users so we resolved to remove the time component, give them one calendar where they can select three days at once. You get @adetola-ralph ?
